// Auto-generated Google Business Profile Local SEO Location Configuration
export const gbpLocation = {
  storeName: "GAS CITY CANNABIS",
  domain: "gascitycannabis.com",
  city: "Toronto",
  province: "ON",
  country: "CA",
  slug: "weed-dispensary-toronto",
  address: "985 O'Connor Dr, Toronto, ON M4B 2T1",
  streetAddress: "985 O'Connor Dr",
  postalCode: "M4B 2T1",
  phone: "(647) 638-1494",
  phoneIntl: "+16476381494",
  neighborhood: "East York / O'Connor",
  nearbyAreas: ["O'Connor Dr", "East York", "Woodbine Ave", "Taylor Creek", "Parkview Hills", "Topham Park", "TTC"],
  products: [
    "Flower",
    "Pre-rolls",
    "Edibles",
    "THC vapes",
    "Concentrates",
    "Shatter",
    "CBD oils",
    "Accessories"
  ],
  menuUrl: "/",
  directionsUrl: "https://gascitycannabis.com/",
  mapEmbedUrl: "https://maps.google.com/maps?q=GAS%20CITY%20CANNABIS%20985%20O%27Connor%20Dr%2C%20Toronto%2C%20ON%20M4B%202T1&t=&z=15&ie=UTF8&iwloc=&output=embed",
  latitude: "43.7086100",
  longitude: "-79.3101300",
  hours: ["Open Daily: 10:00 AM - 03:00 AM"],
  seoTitle: "GAS CITY CANNABIS | Weed Dispensary in Toronto",
  metaDescription: "GAS CITY CANNABIS is a local weed dispensary in Toronto offering flower, pre-rolls, edibles, vapes, concentrates, CBD, and service for adults 19+.",
  localLandmarks: ["O'Connor Dr", "East York", "Woodbine Ave"],
  introVariant: "Welcome to GAS CITY CANNABIS, your premier weed dispensary in Toronto situated right on 985 O'Connor Dr. We are dedicated to providing adults 19+ with top-tier weed, premium cannabis flower, pre-rolls, edibles, THC vapes, concentrates, and CBD products. If you are looking for a trusted cannabis store near East York / O'Connor or a weed shop near East York, stop by today to consult with our knowledgeable staff.",
  neighborhoodDescription: "Located in the vibrant East York / O'Connor district, our cannabis store fits right into this active and historic community, surrounded by local retail shops and convenient transit links.",
  parkingNote: "Parking spaces are available in the plaza lot",
  transitNote: "Easily accessible via local TTC bus routes serving O'Connor Drive.",
  sectionTitle: "Serving Customers Near East York in Toronto"
};
